services:
  mongo:
    image: mongo:8.0
    container_name: syncflow_mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: syncflow_local
    volumes:
      - mongo_data:/data/db
      - ./mongo-init/init.js:/docker-entrypoint-initdb.d/init.js:ro

  redis:
    image: redis:6.2-alpine
    container_name: syncflow_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # 可选：数据库管理界面 (访问 localhost:8081)
  mongo-express:
    image: mongo-express
    container_name: syncflow_ui
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: pass
    depends_on:
      - mongo

volumes:
  mongo_data:
  redis_data: